{"name": "Успешный вход в систему для существующего пользователя с верными данными", "status": "passed", "steps": [{"name": "Авторизация пользователя", "status": "passed", "parameters": [{"name": "user", "value": "<data.data.User object at 0x000002B230E122C0>"}], "start": 1736340090860, "stop": 1736340091111}], "start": 1736340090860, "stop": 1736340091111, "uuid": "98074f28-e7f3-468d-9d11-5d7f41c1acc9", "historyId": "3047e1353a50ac34cd518eefb0fb6eba", "testCaseId": "3047e1353a50ac34cd518eefb0fb6eba", "fullName": "tests.auth.test_user_login.TestUserLogin#test_login_by_existing_user_with_correct_data_returns_success", "labels": [{"name": "parentSuite", "value": "tests.auth"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-2S7589E"}, {"name": "thread", "value": "2324-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.auth.test_user_login"}]}